Comfy-Org/docs

README.md
mint.json

- noticed a 404 error when user clicks 'documentation' on hamburger sidebar because it was redirecting to our old url

update 404 error url docs.drip.art to comfydocs.org

---

registry/overview.mdx

Added the video directly under 
but can move it down to the bottom of the page too!
The tutorial video: https://youtu.be/WhOZZOgBggU?si=wXSQKvvavuf1On8z

Add Registry Tutorial Video 

---

essentials/custom_node_images_and_masks.mdx

Appreciate the effort put into the documentation and site. It  deserves more visibility. I often see people on Reddit/Discord looking for good docs for creating nodes.
I've suggested some edits for the MASK section.
There was some things that I thought might be slightly incorrect, but I could be wrong. The documentation states that masks have a default shape of `[B, H, W, C]`, but my understanding is that masks are created by calling `numpy.array()` on the alpha channel of a `PIL.Image.Image`, which creates a 2D array since it's a single channel. When it's then converted to a tensor, it will be `[B, H, W]`. 
Although I do remember at one point being in a scenario where I was getting `[B, H, W, C]` masks, so I understand why it was written. 
There's also note at the bottom of the page that …

Edited MASK section of docs

---

registry/specifications.mdx

Casing currently isn't mentioned anywhere!

Specify toml file name to add 'lowercase' to requirements

---

.notes/topics.md
essentials/custom_node_images_and_masks.mdx
essentials/custom_node_snippets.mdx
essentials/custom_node_tensors.mdx
essentials/custom_node_walkthrough.mdx
mint.json

Moved some of the mask and image code examples into a new code examples page.
Moved the more technical torch.Tensor stuff into its own page and expanded it somewhat.

Masks and tensors and examples

---

registry/overview.mdx
registry/specifications.mdx

- specified .txt in LICENSE field
- added semver examples in version number 
- explicitly labelled what we expect [FILE PATHS, URLS, etc.] for more ambiguous fields [LICENSE, ICON]

Update PyProject Toml Specs Page

---

registry/overview.mdx
registry/specifications.mdx

- based on convo with DoctorPangloss we realized that there was an error in the way we were asking people to specify License paths
- should be license = {file = "LICENSE.txt" } , not license = "LICENSE.txt"

Update License File Naming

---

essentials/javascript_examples.mdx
essentials/javascript_settings.mdx
mint.json

The sample code provided on the Examples page uses a deprecated way of adding settings and is missing a lot of details.
The new page shows the new way of doing things and explains the different data types, options, and events.

Add a new Settings page in the Client side section

---

essentials/comms_routes.mdx
essentials/custom_node_workflow_templates.mdx
mint.json

Documentation to support custom node developers regarding a recently implemented feature.  
See https://github.com/Comfy-Org/ComfyUI_frontend/pull/2032 for details.

Add documentation for custom workflow templates feature

---

custom-nodes/js/javascript_hooks.mdx

Use `nodeType.comfyClass` instead of `nodeType.ComfyClass`.

Fix typo in `beforeRegisterNodeDef` hook example

---

custom-nodes/backend/datatypes.mdx

- Edited Part: https://docs.comfy.org/custom-nodes/backend/datatypes#tensor-datatypes
Added `AUDIO` for Tensor datatype.
The AUDIO format looks like this:
```python
{"sample_rate": 16000, "waveform": <torch.Tensor>}
```
It would be helpful to include this in the doc for nodes that involve audio (e.g. TTS nodes)

Add `AUDIO` for Tensor datatype

---

zh-CN/installation/desktop/macos.mdx

- Corrected "MacOS" to "macOS" within the Chinese translation (`zh-CN/installation/desktop/macos.mdx`) per Apple style guide.
- Applied minor punctuation and wording fixes for clarity within the same file.

style: Correct macOS capitalization in zh-CN macOS install guide

---

tutorials/image/hidream/hidream-i1.mdx

The link previously pointed to the fp8 variant.

fixed link to hidream_i1_fast_bf16.safetensors

---

installation/desktop/windows.mdx

This PR capitalizes Windows and replaces the network wired icon with the windows logo, aligning with MacOS and Linux.
Before:
After:

Windows sidebar style nit

---

tutorials/audio/ace-step/ace-step-v1.mdx
zh-CN/tutorials/audio/ace-step/ace-step-v1.mdx

- correct link to ACE-Step audio-to-audio example workflow in both English and Chinese docs
- `npm run lint` *(fails: Missing script)*

Fix ACE-Step example workflow download link

---

custom-nodes/backend/snippets.mdx

- fix repeated word in custom nodes snippets doc
- `npm run dev` *(fails: command aborted due to environment)*

Fix typo in backend snippets doc

---

custom-nodes/js/javascript_about_panel_badges.mdx
custom-nodes/js/javascript_bottom_panel_tabs.mdx
custom-nodes/js/javascript_commands_keybindings.mdx
custom-nodes/js/javascript_dialog.mdx
custom-nodes/js/javascript_sidebar_tabs.mdx
custom-nodes/js/javascript_toast.mdx
custom-nodes/js/javascript_topbar_menu.mdx
docs.json

Add comprehensive documentation for 6 previously undocumented frontend JavaScript APIs including Dialog, Toast, About Panel Badges, Bottom Panel Tabs, Sidebar Tabs, and Commands/Keybindings. Each API page includes basic usage, configuration options, and practical examples.

Add documentation for frontend developer APIs

---

interface/appearance.mdx
zh-CN/interface/appearance.mdx

Corrects the color palette JSON example in appearance.mdx to match the actual ComfyUI schema structure with proper id, name, colors wrapper, and accurate property names.
To verify, see actual examples of valid color palettes here: https://github.com/Comfy-Org/ComfyUI_frontend/tree/main/src/assets/palettes

[docs] Fix invalid color palette JSON example

---

interface/appearance.mdx
snippets/install/user-directory.mdx
zh-CN/interface/appearance.mdx

Fixes broken snippet imports in appearance pages that were using deprecated syntax instead of proper import statements. Also improves the user directory snippet by organizing paths into clear tabs by installation type for better user experience.
Before:
After:
Fixes #135

[fix] Fix user directory snippet import syntax and improve layout

---

.github/workflows/zh-cn-sync-check.yml

Don't exit with status code > 0 if grep/diff fails and fix issue described below:
> Looking at the debug logs, I can see the issue. The
>   problem is in the way shell arrays are being used in
>   GitHub Actions. The main issue is:
> 
>   1. Array initialization syntax: Lines like
>   MOVED_FILES=() and MISSING_TRANSLATIONS=() work in bash,
>    but there are additional issues with how the arrays are
>    being handled in the GitHub Actions environment.
>   2. The specific error: Looking at the debug logs, I can
>   see that the script is failing because when GitHub
>   Actions processes the workflow, it's having trouble with
>    the double curly braces ${{}} syntax when it's mixed
>   with shell array operations.
> 
>   The issue is that GitHub Actions is trying to evaluate
> …

Fix: Chinese Translation Sync Check always fails

---

.claude/commands/verify-visually.md
.mcp.json
package-lock.json
package.json

Integrates Playwright MCP server to enable automated browser testing and visual verification of documentation changes. Includes a custom Claude Code command for systematic visual regression testing.

[feat] Add Playwright MCP integration for visual testing

---

troubleshooting/custom-node-issues.mdx
zh-CN/troubleshooting/custom-node-issues.mdx

Adds automated bisect option using comfy-cli as the recommended method for finding problematic custom nodes, while keeping the manual binary search process as an alternative. Fixes #138

[docs] add comfy-cli bisect tool to custom node troubleshooting

---

custom-nodes/backend/interface.mdx
custom-nodes/help-page.mdx
docs.json
zh-CN/custom-nodes/help-page.mdx

Added documentation for a new feature that allows custom node authors to include rich markdown documentation in their WEB_DIRECTORY/docs folder. The documentation will be displayed in the UI instead of generic node descriptions, supporting localization and multimedia content.
Could the Chinese translation be reviewed? It was generated.
Related Frontend PR: https://github.com/Comfy-Org/ComfyUI_frontend/pull/3922
Related Core PR: https://github.com/comfyanonymous/ComfyUI/pull/8179

Add custom node markdown documentation feature

---

installation/comfyui_portable_windows.mdx
zh-CN/installation/comfyui_portable_windows.mdx

Since the portable version now supports PyTorch 3.7, there is no need for additional explanation regarding the 50 series graphics cards. 
But we may need to improve the part of the dependency-related instructions. Currently, this part is still in a very preliminary state and will take some time to complete.

Remove note about 50 series GPU

---

get_started/first_generation.mdx
snippets/install/add-external-models.mdx
snippets/install/external-models-desktop.mdx
snippets/install/troubleshooting-feedback.mdx
snippets/zh/install/troubleshooting-feedback.mdx
zh-CN/get_started/first_generation.mdx
zh-CN/snippets/install/add-external-models.mdx
zh-CN/snippets/install/external-models-desktop.mdx
zh-CN/snippets/install/troubleshooting-feedback.mdx
zh-CN/snippets/zh/install/troubleshooting-feedback.mdx

Fixes incorrect YAML property names in model path configuration docs. Changes custom property names to standard ComfyUI model type names (loras, checkpoints, etc.) so models are properly recognized. Fixes #166

[docs] fix external model paths configuration examples

---

custom-nodes/backend/tensors.mdx

Description:  
This pull request corrects a typo in the documentation for elementwise operations in tensors. The word "independantly" has been replaced with the correct spelling "independently" in the file custom-nodes/backend/tensors.mdx. No functional code changes were made; this update is purely for documentation clarity and accuracy.

Fix Typo in Elementwise Operations Documentation

---

registry/cicd.mdx

**Description:**  
This pull request corrects a typo in the `registry/cicd.mdx` file, changing "commiting" to the correct spelling "committing" in the documentation. No other content was modified. This improves the clarity and professionalism of the documentation.

Fix typo in CI/CD documentation 

---

troubleshooting/model-issues.mdx
zh-CN/troubleshooting/model-issues.mdx

Adds the common tensor multiplication error that occurs when mixing ControlNet architectures. Updates both English and Chinese docs to help users diagnose SD1.5/SDXL ControlNet compatibility issues.

[docs] Add ControlNet architecture mismatch error to troubleshooting

---

interface/settings/lite-graph.mdx

Changed the page title and sidebar title to clarify the relationship between ComfyUI, LiteGraph, and the Canvas. This improves clarity for users navigating the settings documentation.

Update LiteGraph settings page titles

---

interface/shortcuts.mdx
zh-CN/interface/shortcuts.mdx

Revised shortcut descriptions to use 'Queue prompt' instead of 'Execute prompt' and updated the workflow clearing shortcut to use only Backspace instead of Ctrl/Cmd + Delete/Backspace in both English and Chinese documentation.

Update shortcut descriptions and workflow clearing keys

---

changelog/index.mdx
zh-CN/changelog/index.mdx

Update changelog with comfyui version 0.3.41
This PR updates the existing changelog by prepending the new release notes.
Files updated:
changelog/index.mdx
- zh-CN/changelog/index.mdx
Generated from GitHub release webhook and processed with Anthropic AI.
Strapi Draft ID: 34

Update changelog with comfyui v0.3.41

---

installation/desktop/macos.mdx
zh-CN/installation/desktop/macos.mdx

[I submitted ComfyUI Desktop to Homebrew](https://github.com/Homebrew/homebrew-cask/pull/207593) and it's been available there for some time, it would be awesome if this is also mentioned in the official docs, instead of having to be discovered by users themselves.

Add Homebrew install instruction

---

custom-nodes/js/javascript_selection_toolbox.mdx
docs.json
zh-CN/custom-nodes/js/javascript_selection_toolbox.mdx

Add tutorial for add items to the selection toolbox as an extension developer.
Fixes #313

[docs] add "Selection Toolbox" API documentation (UI extension development)
