README.md

Update discord link.

---

.notes/topics.md
essentials/custom_node_datatypes.mdx
essentials/custom_node_more_on_inputs.mdx
essentials/custom_node_tensors.mdx
essentials/javascript_objects_and_hijacking.mdx
mint.json

I'll close #20 and #21, this contains them all.
And I'll learn how to do stacked PR's properly :)

Roll up of recent changes

---

.notes/topics.md
essentials/custom_node_datatypes.mdx
essentials/custom_node_lists.mdx
essentials/custom_node_server_overview.mdx
essentials/custom_node_snippets.mdx
mint.json

Added description of how INPUT_IS_LIST and OUTPUT_IS_LIST operate.
Also a brief description of VALIDATE_INPUTS for completeness.
Added a bit more on NOISE, and some example code showing it in use.

list handling and a few other bits

---

registry/overview.mdx
registry/specifications.mdx

- updated copy paste warning message for api key
- added another example of acceptable license format

update license specs + edit api key commit

---

essentials/custom_node_datatypes.mdx
essentials/custom_node_expansion.mdx
essentials/custom_node_lazy_evaluation.mdx
essentials/custom_node_more_on_inputs.mdx
essentials/custom_node_server_overview.mdx
essentials/execution_model_inversion_guide.mdx
essentials/execution_order.mdx
mint.json

This PR updates documentation for the changes from the Execution Model Inversion PR.
I also fixed some incorrect documentation I found.

Add documentation on Execution Model Inversion

---

essentials/custom_node_expansion.mdx
essentials/custom_node_lazy_evaluation.mdx
essentials/custom_node_more_on_inputs.mdx

Some last minute changes moved some files around (commit 5960f94).
This PR updates docs for those new paths. I've also added some docs
on the `ExecutionBlocker`.

Update documentation on execution inversion

---

get_started/gettingstarted.mdx

Closes https://github.com/Comfy-Org/docs/issues/37

Replace dead sd 1.5 link

---

custom-nodes/backend/datatypes.mdx

Added `BOOLEAN` for Python datatype

Add `BOOLEAN` for Python datatype

---

package.json

minor nit, npm run dev is just a standard nice to have convention for npx mintlify dev

Add npm run dev

---

index.mdx

Whitespace nit

---

docs.json
zh-CN/essentials/comfyui-server/comms_messages.mdx
zh-CN/essentials/comfyui-server/comms_overview.mdx
zh-CN/essentials/comfyui-server/execution_model_inversion_guide.mdx

-   [x] **Chinese Translations Added:**
-   [x] `essentials/comfyui-server/execution_model_inversion_guide.mdx`
-   [x] `essentials/comfyui-server/comms_overview.mdx`
-   [x] `essentials/comfyui-server/comms_messages.mdx`
-   [x] **Navigation Updated (`docs.json`):**
These changes improve documentation accessibility for Chinese-speaking users.

feat(i18n): Add Chinese translations for ComfyUI Server docs

---

docs.json
essentials/comfyui-server/api-key-integration.mdx
tutorials/api-nodes/overview.mdx
zh-CN/essentials/comfyui-server/api-key-integration.mdx
zh-CN/tutorials/api-nodes/overview.mdx

About how to integrate an ComfyUI API key to use API nodes

ComfyUI API Key Integration

---

README.md
docs.json

Error reported in [Discord](https://discord.com/channels/1218270712402415686/1243610878314807337/1361997824354418809).
```bash
benja@DESKTOP-SN2QI9B MINGW64 ~/ComfyOrg/docs (main)
$ npm i mintlify
npm warn deprecated mdast@3.0.0: `mdast` was renamed to `remark`
added 733 packages, and audited 734 packages in 24s
321 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
benja@DESKTOP-SN2QI9B MINGW64 ~/ComfyOrg/docs (main)
$ npx mintlify dev
✖ Cannot convert undefined or null to object
```
--> deleted node_modules here
```bash
benja@DESKTOP-SN2QI9B MINGW64 ~/ComfyOrg/docs (main)
$ npm i
added 677 packages, and audited 678 packages in 6s
321 packages are looking for funding
run `npm fund` for details
1 high severity vulnerability
To address all issues, run:
npm …
```

Fix dev setup

---

docs.json

Been endlessly scouring the nav for this page way too many times 😅

Added link to Routes in main nav;

---

docs.json
snippets/zh/cli-reference/models.mdx
snippets/zh/cli-reference/nodes.mdx
snippets/zh/install-comfy-from-cli.mdx
snippets/zh/install-comfycli.mdx
zh-CN/comfy-cli/getting-started.mdx
zh-CN/comfy-cli/reference.mdx

I thought `comfy-cli\troubleshooting.mdx` is stale?
And I translate the comfy-cli docs into zh-CN, please review it.

feat: Add zh-CN version to comfy-cli

---

.github/workflows/redirect-check.yml
.github/workflows/zh-cn-sync-check.yml
README.md
README.zh-CN.md

Add Github action to test the following: 
- If a file is edited, make sure the Chinese file is edited as well
- If a file is moved, make sure a redirect is added

CI: Check if chinese versions are added

---

docs.json

Revert "Add Registry API reference and pricing updates"

---

registry/specifications.mdx
zh-CN/registry/specifications.mdx

Updates the Complete Example section in the pyproject.toml documentation to include frontend version compatibility and requires-comfyui properties that were missing from the example but documented in the article body.
Fixes #159

[docs] Update pyproject.toml complete example with missing properties

---

changelog/index.mdx
docs.json
zh-CN/changelog/index.mdx

Adds dedicated changelog pages to the documentation site to support automated release note publishing and provide users with a centralized location to track ComfyUI updates.
- **English Changelog**: Added `changelog/index.mdx` with proper frontmatter and clock icon
- **Chinese Changelog**: Added `zh-CN/changelog/index.mdx` with localized title and description
- **Navigation Integration**: Updated `docs.json` to include changelog links in both English and Chinese navigation menus
- **Code Formatting**: Improved JSON formatting consistency throughout `docs.json`
These changelog pages serve as:
- **Automated Publishing Target**: Destination for release notes generated via GitHub webhooks
- **User Reference**: Centralized location for users to view all ComfyUI updates
- **Bilingual Support**: …

[System Pop Up] Add changelog pages for release notes integration

---

installation/update_comfyui.mdx
snippets/zh/tutorials/update-reminder.mdx
troubleshooting/custom-node-issues.mdx
zh-CN/installation/update_comfyui.mdx
zh-CN/troubleshooting/custom-node-issues.mdx

Improved instructions in update and troubleshooting documentation for both English and Chinese versions. Clarified environment usage for dependency updates, fixed a link path, and standardized heading levels for better readability and consistency.

Refine update and troubleshooting docs for clarity

---

development/comfyui-server/comms_messages.mdx
zh-CN/development/comfyui-server/comms_messages.mdx

Added info about "execution_success" websocket message to `/development/comfyui-server/comms_messages`

Added info about "execution_success" websocket message

---

tutorials/flux/flux-1-kontext-dev.mdx
zh-CN/tutorials/flux/flux-1-kontext-dev.mdx

Added YouTube and Bilibili video iframes to the English and Chinese Flux.1 Kontext Dev tutorial pages, respectively, to showcase new features of the ComfyUI Selection Toolbox.

Embed video iframes in Flux.1 Kontext Dev tutorials

---

docs.json
giscus-comments.js

Fix comment section styling when using light mode; also solved https://github.com/comfyanonymous/ComfyUI/issues/8978

Styling issue

---

changelog/index.mdx
zh-CN/changelog/index.mdx

Update changelog with comfyui version 0.3.52
This PR updates the existing changelog by prepending the new release notes.
Files updated:
changelog/index.mdx
- zh-CN/changelog/index.mdx
Generated from GitHub release webhook and processed with Anthropic AI.
Strapi Draft ID: 315

Update changelog with comfyui v0.3.52

---

changelog/index.mdx
zh-CN/changelog/index.mdx

Update changelog with comfyui version 0.3.56
This PR updates the existing changelog by prepending the new release notes.
Files updated:
changelog/index.mdx
- zh-CN/changelog/index.mdx
Generated from GitHub release webhook and processed with Anthropic AI.
Strapi Draft ID: 371

Update changelog with comfyui v0.3.56

---

changelog/index.mdx
zh-CN/changelog/index.mdx

Update changelog with comfyui version 0.3.61
This PR updates the existing changelog by prepending the new release notes.
Files updated:
changelog/index.mdx
- zh-CN/changelog/index.mdx
Generated from GitHub release webhook and processed with Anthropic AI.
Strapi Draft ID: 469

Update changelog with comfyui v0.3.61
